# Generated by Django 2.2.10 on 2020-07-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('sslc', models.CharField(blank=True, max_length=100, null=True)),
                ('hslc', models.CharField(blank=True, max_length=100, null=True)),
                ('cgpa', models.IntegerField()),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=20, null=True)),
                ('achivements', models.TextField()),
                ('skils', models.TextField()),
            ],
        ),
    ]
